### ISSUE TITLE
Panic when downloading without byteswaping

### ISSUE THREAD

**Issue by bigbass1997** [rasky/g64drive#1]
Using Linux release v0.3.1, with a 64drive HW2. Attempting to download data, either without setting the `--byteswap` flag, or setting it to 0 (aka no byteswapping), causes the program to panic. Log: https://gist.github.com/bigbass1997/52cdb8ca2f08aa99878448d79e31efb6

I'm not too familiar with Go, but looking through the code, it appears the issue is that the [BSNone const is set to 1](https://github.com/rasky/g64drive/blob/v0.3.1/drive64/byteswap.go#L14), not 0. And attempting to provide `--byteswap 1` yields an error message:
```
./g64drive-linux64.binary download dump.z64 --size 33554432 --byteswap 1
Error: invalid byteswap value
```

**Comment by rasky** [comment]
Thanks! This was a regression after a refactoring. I'm going to push a new release soon, or you can use the command in the README to compile from source.
